const data = [
  {
    id: "RT3080",
    createdAt: "2021-08-18",
    paymentDue: "2021-08-19",
    description: "Re-branding",
    paymentTerms: 1,
    clientName: "Jensen Huang",
    clientEmail: "jensenh@mail.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "106 Kendell Street",
      city: "Sharrington",
      postCode: "NR24 5WQ",
      country: "United Kingdom",
    },
    items: [
      {
        name: "Brand Guidelines",
        quantity: 1,
        price: 1800.9,
        total: 1800.9,
      },
    ],
    total: 1800.9,
  },
  {
    id: "XM9141",
    createdAt: "2021-08-21",
    paymentDue: "2021-09-20",
    description: "Graphic Design",
    paymentTerms: 30,
    clientName: "Alex Grim",
    clientEmail: "alexgrim@mail.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "84 Church Way",
      city: "Bradford",
      postCode: "BD1 9PB",
      country: "United Kingdom",
    },
    items: [
      {
        name: "Banner Design",
        quantity: 1,
        price: 156.0,
        total: 156.0,
      },
      {
        name: "Email Design",
        quantity: 2,
        price: 200.0,
        total: 400.0,
      },
    ],
    total: 556.0,
  },
  {
    id: "AA9321",
    createdAt: "2021-09-10",
    paymentDue: "2021-09-20",
    description: "UX Review",
    paymentTerms: 10,
    clientName: "Marie Adams",
    clientEmail: "madams@mail.com",
    status: "draft",
    senderAddress: {
      street: "34 Green Lane",
      city: "Bristol",
      postCode: "BS1 4QJ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "12 High Street",
      city: "Bath",
      postCode: "BA1 1AB",
      country: "United Kingdom",
    },
    items: [
      {
        name: "UX Audit",
        quantity: 1,
        price: 950.0,
        total: 950.0,
      },
    ],
    total: 950.0,
  },
  {
    id: "BG2198",
    createdAt: "2021-09-15",
    paymentDue: "2021-10-15",
    description: "Web Development",
    paymentTerms: 30,
    clientName: "Linda Johnson",
    clientEmail: "lindaj@mail.com",
    status: "paid",
    senderAddress: {
      street: "9 Baker Street",
      city: "Manchester",
      postCode: "M1 2AN",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "23 Maple Road",
      city: "Liverpool",
      postCode: "L1 8JQ",
      country: "United Kingdom",
    },
    items: [
      {
        name: "Frontend Dev",
        quantity: 1,
        price: 2400.0,
        total: 2400.0,
      },
      {
        name: "Backend Dev",
        quantity: 1,
        price: 2600.0,
        total: 2600.0,
      },
    ],
    total: 5000.0,
  },
  {
    id: "NP3056",
    createdAt: "2021-10-05",
    paymentDue: "2021-10-20",
    description: "Photography",
    paymentTerms: 15,
    clientName: "Charlie Kim",
    clientEmail: "ckim@mail.com",
    status: "pending",
    senderAddress: {
      street: "77 Rose Street",
      city: "Edinburgh",
      postCode: "EH2 3JG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "99 Gower Street",
      city: "London",
      postCode: "WC1E 6AA",
      country: "United Kingdom",
    },
    items: [
      {
        name: "Product Shoot",
        quantity: 3,
        price: 500.0,
        total: 1500.0,
      },
    ],
    total: 1500.0,
  },
  {
    id: "FH2290",
    createdAt: "2021-10-11",
    paymentDue: "2021-11-10",
    description: "Marketing Campaign",
    paymentTerms: 30,
    clientName: "Olivia Chen",
    clientEmail: "oliviac@mail.com",
    status: "draft",
    senderAddress: {
      street: "61 Hope Street",
      city: "Glasgow",
      postCode: "G2 6AE",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "201 Castle Street",
      city: "Inverness",
      postCode: "IV2 3QZ",
      country: "United Kingdom",
    },
    items: [
      {
        name: "Ad Copywriting",
        quantity: 2,
        price: 300.0,
        total: 600.0,
      },
      {
        name: "Social Media",
        quantity: 1,
        price: 1200.0,
        total: 1200.0,
      },
    ],
    total: 1800.0,
  },
  {
    id: "MK4402",
    createdAt: "2021-11-01",
    paymentDue: "2021-12-01",
    description: "App Design",
    paymentTerms: 30,
    clientName: "Daniel Wu",
    clientEmail: "danielw@mail.com",
    status: "paid",
    senderAddress: {
      street: "42 Canal Street",
      city: "Leeds",
      postCode: "LS2 7EB",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "58 King Street",
      city: "Nottingham",
      postCode: "NG1 2AS",
      country: "United Kingdom",
    },
    items: [
      {
        name: "Wireframe Design",
        quantity: 1,
        price: 1100.0,
        total: 1100.0,
      },
      {
        name: "Prototype",
        quantity: 1,
        price: 1900.0,
        total: 1900.0,
      },
    ],
    total: 3000.0,
  },
];


export default data